export const PATH = {
    INDEX: '/',
    MAIN: '/main',
    FEEDBAKS: '/feedbacks',
    CALENDAR: '/calendar',
    AUTH: '/auth',
    AUTH_CONFIRM_EMAIL: '/auth/confirm-email',
    AUTH_CHANGE_PASS: '/auth/change-password',
    AUTH_REG: '/auth/registration',
    SUCCESS: 'success',
    SUCCESS_PASS_CHANGE: 'success-change-password',
    RESULT: '/result',
    ERROR: '/resulterror',
    ERROR_LOGIN: '/resulterror-login',
    ERROR_USER: '/resulterror-user-exist',
    ERROR_EMAIL: '/result/error-check-email',
    ERROR_EMAIL_NO_EXIST: '/resulterror-check-email-no-exist',
    ERROR_CHANGE_PASS: '/resulterror-change-password',
};
